-- companys_schema.sql
-- Raj Communication: Companies table + seed data from SERVICE COMPANY LIST.pdf

CREATE TABLE IF NOT EXISTS companies (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_code VARCHAR(30) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    product TEXT NOT NULL,
    contact_person VARCHAR(120) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    email VARCHAR(191) DEFAULT NULL,
    address TEXT DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    source_pdf VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_companies_code (company_code),
    KEY idx_companies_name (company_name),
    KEY idx_companies_created_at (created_at),
    KEY idx_companies_source_pdf (source_pdf)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO companies (company_code, company_name, product, contact_person, phone, email, address, notes, source_pdf)
VALUES
('CMP0001', 'SVA MARLKETING', 'ERD PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0002', 'PRAMMA HIKVISION', 'HIKVISION PRODUCT AND PRAMMA PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0003', 'ADITYA INFOTECH', 'CP PLUS ALL PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0004', 'HI FOCUS', 'HIFOCUS PRODUCT, HIXECURE PRODUCT AND UNV PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0005', 'REALTECH VISION', 'N-TECH HDD, MAXXION PRODUCT, TRUEVIEW PRODUCT, IMOU PRODUCT, TIANDY PRODUCT, COFE MODEM, FYBER PRODUCT, TOSHIBA HDD, SECUREMAX PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0006', 'KRYSTAA INFOSYS', 'KRYSTAA ALL PRODUCT ONLY', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0007', 'SUXUS INFOTECH', 'BLUE FEATHER HDD', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0008', 'PELIKAN OFFICE AUTIMATION', 'HIKVISION POWER SUPPLY AND SECUREYE PRODUCT AND SEAGATE HDD', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0009', 'ACEMETRO ELECTRONICS', 'KARBON HDD AND COFE CAMERA AND WESTERN DIGITAL HDD', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0010', 'ZEBRONICS SERVICE CENTER', 'ZEBRONICS ALL PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0011', 'DOWELL TECHNOLOGY', 'GEONIX AND BLUEFEATHER HDD', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0012', 'D-LINK SERVICE / RIPPLES', 'D-LINK PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0013', 'DIGIZONE', 'LANZOEN PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0014', 'DIRECT PRCHASING PLACE', 'WD HDD, SEAGATE HDD, BLUEFEATHER HDD, CONSISTENT HDD', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0015', 'RAJ COMMUNICATION', 'MONITOR, MOUSE, AND OTHER PURCHASED PRODUCT', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0016', 'LOCAL SERVICE CENTER', 'MONITORS AND BIOMETRIC DEVICE', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf'),
('CMP0017', 'DAHUA', 'DAHUA PRODUCT ONLY', '', '', '', '', 'Imported from SERVICE COMPANY LIST.pdf', 'SERVICE COMPANY LIST.pdf');

